version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: oyagema-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl/certs
      - ./public/uploads:/var/www/oyagema/public/uploads
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - nextjs
      - donation-service
    networks:
      - oyagema-network
    restart: unless-stopped

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oyagema-nextjs
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:Kacapirin9!@88.222.212.111:5433/oyagema
      - NEXTAUTH_URL=https://oyagema.com
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DONATION_SERVICE_URL=http://donation-service:5000
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - oyagema-network
    restart: unless-stopped
    depends_on:
      - donation-service

  donation-service:
    build:
      context: ./donation-service
      dockerfile: Dockerfile
    container_name: oyagema-donation-service
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:Kacapirin9!@88.222.212.111:5433/oyagema
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - FRONTEND_URL=https://oyagema.com
    networks:
      - oyagema-network
    restart: unless-stopped

networks:
  oyagema-network:
    driver: bridge

volumes:
  uploads:
    driver: local