version: '3.8'

services:
  # Database PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-oyagema}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - oyagema-network

  # Aplikasi Next.js
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-oyagema}?schema=public
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:8996}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DONATION_SERVICE_URL=http://donation-service:5000
    ports:
      - "8996:8996"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - oyagema-network

  # Donation Service
  donation-service:
    build:
      context: ./donation-service
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - EMAIL_HOST=${EMAIL_HOST:-sandbox.smtp.mailtrap.io}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    ports:
      - "5001:5000"
    restart: unless-stopped
    networks:
      - oyagema-network

volumes:
  postgres_data:

networks:
  oyagema-network:
    driver: bridge