const PAYMENT_GATEWAY_URI = process.env.PAYMENT_URL
const PAYMENT_CLIENT_ID = process.env.CLIENT_ID
const PAYMENT_CLIENT_SECRET = process.env.CLIENT_SECRET
const FRONTEND_URL = process.env.FRONTEND_URL
const DONATION_SERVICE_URL = process.env.DONATION_SERVICE_URL

module.exports = {
  PAYMENT_GATEWAY_URI,
  PAYMENT_CLIENT_ID,
  PAYMENT_CLIENT_SECRET,
  FRONTEND_URL,
  DONATION_SERVICE_URL
}